# Generated by Django 5.2.6 on 2025-09-11 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='otp_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
