# Generated by Django 5.2.6 on 2025-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
