# Generated by Django 5.2.6 on 2025-09-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
    ]
