# Generated by Django 5.2.6 on 2025-09-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_jobseekerprofile_user_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
