# Generated by Django 5.2.6 on 2025-09-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pendinguser_first_name_pendinguser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer'), ('company', 'Company')], default='jobseeker', max_length=20),
        ),
    ]
