# Generated by Django 5.2.6 on 2025-09-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_companyprofile_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='is_admin',
        ),
    ]
