# Generated by Django 5.2.6 on 2025-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_Services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
