# Generated by Django 5.2.6 on 2025-10-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_companyprofile_company_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_Services',
            new_name='company_services',
        ),
    ]
