# Generated by Django 5.2.6 on 2025-10-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_company_services_companyprofile_company_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_cover',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/'),
        ),
    ]
