# Generated by Django 5.2.6 on 2025-09-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default=19, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(default='19', on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
